package com.team3.entity;

/**
 * DtpropertiesId generated by MyEclipse Persistence Tools
 */

public class DtpropertiesId implements java.io.Serializable {

	// Fields

	private Integer id;

	private String property;

	// Constructors

	/** default constructor */
	public DtpropertiesId() {
	}

	/** full constructor */
	public DtpropertiesId(Integer id, String property) {
		this.id = id;
		this.property = property;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProperty() {
		return this.property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtpropertiesId))
			return false;
		DtpropertiesId castOther = (DtpropertiesId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getProperty() == castOther.getProperty()) || (this
						.getProperty() != null
						&& castOther.getProperty() != null && this
						.getProperty().equals(castOther.getProperty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getProperty() == null ? 0 : this.getProperty().hashCode());
		return result;
	}

}