package com.team3.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Orders generated by MyEclipse Persistence Tools
 */

public class Orders implements java.io.Serializable {

	// Fields

	private Long odrId;

	private String odrCustomer;

	private Date odrDate;

	private String odrAddr;

	private String odrStatus;

	private Set ordersLines = new HashSet(0);
	
	private Double total;

	// Constructors

	/** default constructor */
	public Orders() {
	}

	/** minimal constructor */
	public Orders(String odrCustomer, Date odrDate, String odrStatus) {
		this.odrCustomer = odrCustomer;
		this.odrDate = odrDate;
		this.odrStatus = odrStatus;
	}

	/** full constructor */
	public Orders(String odrCustomer, Date odrDate, String odrAddr,
			String odrStatus, Set ordersLines) {
		this.odrCustomer = odrCustomer;
		this.odrDate = odrDate;
		this.odrAddr = odrAddr;
		this.odrStatus = odrStatus;
		this.ordersLines = ordersLines;
	}

	// Property accessors

	public Long getOdrId() {
		return this.odrId;
	}

	public void setOdrId(Long odrId) {
		this.odrId = odrId;
	}

	public String getOdrCustomer() {
		return this.odrCustomer;
	}

	public void setOdrCustomer(String odrCustomer) {
		this.odrCustomer = odrCustomer;
	}

	public Date getOdrDate() {
		return this.odrDate;
	}

	public void setOdrDate(Date odrDate) {
		this.odrDate = odrDate;
	}

	public String getOdrAddr() {
		return this.odrAddr;
	}

	public void setOdrAddr(String odrAddr) {
		this.odrAddr = odrAddr;
	}

	public String getOdrStatus() {
		return this.odrStatus;
	}

	public void setOdrStatus(String odrStatus) {
		this.odrStatus = odrStatus;
	}

	public Set getOrdersLines() {
		return this.ordersLines;
	}

	public void setOrdersLines(Set ordersLines) {
		this.ordersLines = ordersLines;
	}

	public Double getTotal() {
		Iterator it=this.ordersLines.iterator();
		Double totalPrice=new Double(0);
		while(it.hasNext()){
			OrdersLine ol=(OrdersLine) it.next();
			totalPrice+=ol.getPrice();
		}
		return totalPrice;
	}

}