package com.team3.entity;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * SalChance generated by MyEclipse Persistence Tools
 */

public class SalChance implements java.io.Serializable {

	// Fields

	private Long chcId;

	private String chcSource;

	private String chcCustName;

	private String chcTitle;

	private Integer chcRate;

	private String chcLinkman;

	private String chcTel;

	private String chcDesc;

	private Long chcCreateId;

	private String chcCreateBy;

	private Date chcCreateDate;

	private Long chcDueId;

	private String chcDueTo;

	private Date chcDueDate;

	private String chcStatus;

	private Set salPlans = new HashSet(0);

	private List allDue;
	// Constructors

	/** default constructor */
	public SalChance() {
	}

	/** minimal constructor */
	public SalChance(String chcCustName, String chcTitle, Integer chcRate,
			String chcDesc, Long chcCreateId, String chcCreateBy,
			Date chcCreateDate, String chcStatus) {
		this.chcCustName = chcCustName;
		this.chcTitle = chcTitle;
		this.chcRate = chcRate;
		this.chcDesc = chcDesc;
		this.chcCreateId = chcCreateId;
		this.chcCreateBy = chcCreateBy;
		this.chcCreateDate = chcCreateDate;
		this.chcStatus = chcStatus;
	}

	/** full constructor */
	public SalChance(String chcSource, String chcCustName, String chcTitle,
			Integer chcRate, String chcLinkman, String chcTel, String chcDesc,
			Long chcCreateId, String chcCreateBy, Date chcCreateDate,
			Long chcDueId, String chcDueTo, Date chcDueDate, String chcStatus,
			Set salPlans) {
		this.chcSource = chcSource;
		this.chcCustName = chcCustName;
		this.chcTitle = chcTitle;
		this.chcRate = chcRate;
		this.chcLinkman = chcLinkman;
		this.chcTel = chcTel;
		this.chcDesc = chcDesc;
		this.chcCreateId = chcCreateId;
		this.chcCreateBy = chcCreateBy;
		this.chcCreateDate = chcCreateDate;
		this.chcDueId = chcDueId;
		this.chcDueTo = chcDueTo;
		this.chcDueDate = chcDueDate;
		this.chcStatus = chcStatus;
		this.salPlans = salPlans;
	}

	// Property accessors
	
	public Long getChcId() {
		return this.chcId;
	}

	public void setChcId(Long chcId) {
		this.chcId = chcId;
	}

	public String getChcSource() {
		return this.chcSource;
	}

	public void setChcSource(String chcSource) {
		this.chcSource = chcSource;
	}

	public String getChcCustName() {
		return this.chcCustName;
	}

	public void setChcCustName(String chcCustName) {
		this.chcCustName = chcCustName;
	}

	public String getChcTitle() {
		return this.chcTitle;
	}

	public void setChcTitle(String chcTitle) {
		this.chcTitle = chcTitle;
	}

	public Integer getChcRate() {
		return this.chcRate;
	}

	public void setChcRate(Integer chcRate) {
		this.chcRate = chcRate;
	}

	public String getChcLinkman() {
		return this.chcLinkman;
	}

	public void setChcLinkman(String chcLinkman) {
		this.chcLinkman = chcLinkman;
	}

	public String getChcTel() {
		return this.chcTel;
	}

	public void setChcTel(String chcTel) {
		this.chcTel = chcTel;
	}

	public String getChcDesc() {
		return this.chcDesc;
	}

	public void setChcDesc(String chcDesc) {
		this.chcDesc = chcDesc;
	}

	public Long getChcCreateId() {
		return this.chcCreateId;
	}

	public void setChcCreateId(Long chcCreateId) {
		this.chcCreateId = chcCreateId;
	}

	public String getChcCreateBy() {
		return this.chcCreateBy;
	}

	public void setChcCreateBy(String chcCreateBy) {
		this.chcCreateBy = chcCreateBy;
	}

	public Date getChcCreateDate() {
		return this.chcCreateDate;
	}

	public void setChcCreateDate(Date chcCreateDate) {
		this.chcCreateDate = chcCreateDate;
	}

	public void setChcCreateDateString(String datetime){
		Date date = new Date();
		System.out.print(datetime.substring(5,7));
		this.chcCreateDate=date;
	}
	public String getChcCreateDateString(){
		SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return date.format(this.chcCreateDate);
	}
	public String getChcCreateDateChString(){
		SimpleDateFormat date=new SimpleDateFormat("yyyy年MM月dd日 HH时mm分ss秒");
		return date.format(this.chcCreateDate);
	}
	
	public Long getChcDueId() {
		return this.chcDueId;
	}

	public void setChcDueId(Long chcDueId) {
		this.chcDueId = chcDueId;
	}

	public String getChcDueTo() {
		return this.chcDueTo;
	}

	public void setChcDueTo(String chcDueTo) {
		this.chcDueTo = chcDueTo;
	}

	public Date getChcDueDate() {
		return this.chcDueDate;
	}

	public String getChcDueDateString(){
		SimpleDateFormat format=new SimpleDateFormat("yyyy年MM月dd日 HH时mm分ss秒");
		return format.format(this.chcDueDate);
	}
	public void setChcDueDate(Date chcDueDate) {
		this.chcDueDate = chcDueDate;
	}

	public String getChcStatus() {
		return this.chcStatus;
	}

	public String getChcStatusString(){
		String ret="null";
		if(this.chcStatus.trim().equals("2")){
			ret="开发中";
		}
		if(this.chcStatus.trim().equals("4")){
			ret="已归档";
		}
		return ret;
	}
	public void setChcStatus(String chcStatus) {
		this.chcStatus = chcStatus;
	}

	public Set getSalPlans() {
		return this.salPlans;
	}

	public void setSalPlans(Set salPlans) {
		this.salPlans = salPlans;
	}

	public List getAllDue() {
		return allDue;
	}

	public void setAllDue(List allDue) {
		this.allDue = allDue;
	}

}