package com.team3.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * SysRole generated by MyEclipse Persistence Tools
 */

public class SysRole implements java.io.Serializable {

	// Fields

	private Long roleId;

	private String roleName;

	private String roleDesc;

	private Integer roleFlag;

	private Set sysUsers = new HashSet(0);

	private Set sysRights = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysRole() {
	}

	/** minimal constructor */
	public SysRole(String roleName) {
		this.roleName = roleName;
	}

	/** full constructor */
	public SysRole(String roleName, String roleDesc, Integer roleFlag,
			Set sysUsers, Set sysRoleRights) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.roleFlag = roleFlag;
		this.sysUsers = sysUsers;
		this.sysRights = sysRoleRights;
	}

	// Property accessors

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Integer getRoleFlag() {
		return this.roleFlag;
	}

	public void setRoleFlag(Integer roleFlag) {
		this.roleFlag = roleFlag;
	}
	
	public String getRoleFlagString(){
		String ret="";
		switch (this.roleFlag) {
		case 0:
			ret="ÒÑÉ¾³ý";
			break;
		case 1:
			ret="Õý³£";
			break;
		}
		return ret;
	}

	public Set getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set sysUsers) {
		this.sysUsers = sysUsers;
	}

	public Set getSysRights() {
		return sysRights;
	}

	public void setSysRights(Set sysRights) {
		this.sysRights = sysRights;
	}

}