package com.team3.entity;

import java.util.List;

/**
 * SysUser generated by MyEclipse Persistence Tools
 */

public class SysUser implements java.io.Serializable {

	// Fields

	private Long usrId;

	private SysRole sysRole;

	private String usrName;

	private String usrPassword;

	private Integer usrFlag;
	
	private List allRole;

	// Constructors

	/** default constructor */
	public SysUser() {
	}

	/** minimal constructor */
	public SysUser(String usrName, String usrPassword, Integer usrFlag) {
		this.usrName = usrName;
		this.usrPassword = usrPassword;
		this.usrFlag = usrFlag;
	}

	/** full constructor */
	public SysUser(SysRole sysRole, String usrName, String usrPassword,
			Integer usrFlag) {
		this.sysRole = sysRole;
		this.usrName = usrName;
		this.usrPassword = usrPassword;
		this.usrFlag = usrFlag;
	}

	// Property accessors

	public Long getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Long usrId) {
		this.usrId = usrId;
	}

	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	public Integer getUsrFlag() {
		return this.usrFlag;
	}

	public void setUsrFlag(Integer usrFlag) {
		this.usrFlag = usrFlag;
	}

	public String getUsrFlagString(){
		String ret="";
		switch (this.usrFlag) {
		case 0:
			ret="ÒÑÉ¾³ý";
			break;
		case 1:
			ret="Õý³£";
			break;
		}
		return ret;
	}

	public List getAllRole() {
		return allRole;
	}

	public void setAllRole(List allRole) {
		this.allRole = allRole;
	}
}